name: Release pluk.sh and pluk.ps1

on:
  push:
    tags:
      - "v*" # new version triggers release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history & tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make installer scripts executable
        run: |
          chmod +x pluk.sh || true
          chmod +x pluk.ps1 || true

      - name: Compute SHA256 checksums
        id: checksum
        run: |
          sha256sum pluk.sh | awk '{print $1}' > pluk.sh.sha256
          sha256sum pluk.ps1 | awk '{print $1}' > pluk.ps1.sha256
          echo "sh_checksum=$(cat pluk.sh.sha256)" >> "$GITHUB_OUTPUT"
          echo "ps1_checksum=$(cat pluk.ps1.sha256)" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release and upload assets
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}

            Installer commands:

            **Unix / Linux / macOS (or Git Bash):**
            ```
            curl -sSL https://cdn.jsdelivr.net/gh/${{ github.repository }}@${{ github.ref_name }}/pluk.sh | bash
            ```

            **Windows PowerShell:**
            ```
            pwsh -NoProfile -ExecutionPolicy Bypass -Command "Invoke-Expression (Invoke-WebRequest https://cdn.jsdelivr.net/gh/${{ github.repository }}@${{ github.ref_name }}/pluk.ps1).Content)"
            ```

            SHA256 checksums:
            - pluk.sh: `${{ steps.checksum.outputs.sh_checksum }}`
            - pluk.ps1: `${{ steps.checksum.outputs.ps1_checksum }}`

          files: |
            pluk.sh
            pluk.sh.sha256
            pluk.ps1
            pluk.ps1.sha256
